// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module GaussianP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        eventX,
        eventY,
        x,
        y,
        sigmaX,
        sigmaY,
        sigmaXY,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 5'd1;
parameter    ap_ST_fsm_pp0_stage1 = 5'd2;
parameter    ap_ST_fsm_pp0_stage2 = 5'd4;
parameter    ap_ST_fsm_pp0_stage3 = 5'd8;
parameter    ap_ST_fsm_pp0_stage4 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [31:0] eventX;
input  [31:0] eventY;
input  [63:0] x;
input  [63:0] y;
input  [63:0] sigmaX;
input  [63:0] sigmaY;
input  [63:0] sigmaXY;
output  [63:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_state5_pp0_stage4_iter0;
wire    ap_block_state10_pp0_stage4_iter1;
wire    ap_block_state15_pp0_stage4_iter2;
wire    ap_block_state20_pp0_stage4_iter3;
wire    ap_block_state25_pp0_stage4_iter4;
wire    ap_block_state30_pp0_stage4_iter5;
wire    ap_block_state35_pp0_stage4_iter6;
wire    ap_block_state40_pp0_stage4_iter7;
wire    ap_block_state45_pp0_stage4_iter8;
wire    ap_block_state50_pp0_stage4_iter9;
wire    ap_block_state55_pp0_stage4_iter10;
wire    ap_block_state60_pp0_stage4_iter11;
wire    ap_block_state65_pp0_stage4_iter12;
wire    ap_block_state70_pp0_stage4_iter13;
wire    ap_block_state75_pp0_stage4_iter14;
wire    ap_block_state80_pp0_stage4_iter15;
wire    ap_block_state85_pp0_stage4_iter16;
wire    ap_block_state90_pp0_stage4_iter17;
wire    ap_block_state95_pp0_stage4_iter18;
wire    ap_block_state100_pp0_stage4_iter19;
wire    ap_block_state105_pp0_stage4_iter20;
wire    ap_block_state110_pp0_stage4_iter21;
wire    ap_block_state115_pp0_stage4_iter22;
wire    ap_block_pp0_stage4_11001;
reg   [63:0] sigmaXY_read_reg_271;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
wire    ap_block_state11_pp0_stage0_iter2;
wire    ap_block_state16_pp0_stage0_iter3;
wire    ap_block_state21_pp0_stage0_iter4;
wire    ap_block_state26_pp0_stage0_iter5;
wire    ap_block_state31_pp0_stage0_iter6;
wire    ap_block_state36_pp0_stage0_iter7;
wire    ap_block_state41_pp0_stage0_iter8;
wire    ap_block_state46_pp0_stage0_iter9;
wire    ap_block_state51_pp0_stage0_iter10;
wire    ap_block_state56_pp0_stage0_iter11;
wire    ap_block_state61_pp0_stage0_iter12;
wire    ap_block_state66_pp0_stage0_iter13;
wire    ap_block_state71_pp0_stage0_iter14;
wire    ap_block_state76_pp0_stage0_iter15;
wire    ap_block_state81_pp0_stage0_iter16;
wire    ap_block_state86_pp0_stage0_iter17;
wire    ap_block_state91_pp0_stage0_iter18;
wire    ap_block_state96_pp0_stage0_iter19;
wire    ap_block_state101_pp0_stage0_iter20;
wire    ap_block_state106_pp0_stage0_iter21;
wire    ap_block_state111_pp0_stage0_iter22;
wire    ap_block_state116_pp0_stage0_iter23;
reg    ap_block_pp0_stage0_11001;
reg   [63:0] sigmaXY_read_reg_271_pp0_iter1_reg;
reg   [63:0] sigmaXY_read_reg_271_pp0_iter2_reg;
reg   [63:0] sigmaXY_read_reg_271_pp0_iter3_reg;
reg   [63:0] sigmaXY_read_reg_271_pp0_iter4_reg;
reg   [63:0] sigmaY_read_reg_277;
reg   [63:0] sigmaY_read_reg_277_pp0_iter1_reg;
reg   [63:0] sigmaY_read_reg_277_pp0_iter2_reg;
reg   [63:0] sigmaY_read_reg_277_pp0_iter3_reg;
reg   [63:0] sigmaX_read_reg_283;
reg   [63:0] sigmaX_read_reg_283_pp0_iter1_reg;
reg   [63:0] sigmaX_read_reg_283_pp0_iter2_reg;
reg   [63:0] sigmaX_read_reg_283_pp0_iter3_reg;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state7_pp0_stage1_iter1;
wire    ap_block_state12_pp0_stage1_iter2;
wire    ap_block_state17_pp0_stage1_iter3;
wire    ap_block_state22_pp0_stage1_iter4;
wire    ap_block_state27_pp0_stage1_iter5;
wire    ap_block_state32_pp0_stage1_iter6;
wire    ap_block_state37_pp0_stage1_iter7;
wire    ap_block_state42_pp0_stage1_iter8;
wire    ap_block_state47_pp0_stage1_iter9;
wire    ap_block_state52_pp0_stage1_iter10;
wire    ap_block_state57_pp0_stage1_iter11;
wire    ap_block_state62_pp0_stage1_iter12;
wire    ap_block_state67_pp0_stage1_iter13;
wire    ap_block_state72_pp0_stage1_iter14;
wire    ap_block_state77_pp0_stage1_iter15;
wire    ap_block_state82_pp0_stage1_iter16;
wire    ap_block_state87_pp0_stage1_iter17;
wire    ap_block_state92_pp0_stage1_iter18;
wire    ap_block_state97_pp0_stage1_iter19;
wire    ap_block_state102_pp0_stage1_iter20;
wire    ap_block_state107_pp0_stage1_iter21;
wire    ap_block_state112_pp0_stage1_iter22;
wire    ap_block_pp0_stage1_11001;
reg   [63:0] y_read_reg_299;
reg   [63:0] x_read_reg_304;
wire   [63:0] grp_fu_132_p1;
reg   [63:0] tmp_reg_309;
wire   [63:0] grp_fu_103_p2;
reg   [63:0] tmp_23_reg_314;
wire   [63:0] grp_fu_109_p2;
reg   [63:0] tmp_24_reg_319;
reg   [63:0] tmp_s_reg_324;
wire   [63:0] grp_fu_99_p2;
reg   [63:0] p_x_assign_reg_329;
reg   [63:0] deltaX_reg_334;
wire   [63:0] determinant_fu_166_p1;
reg   [63:0] determinant_reg_341;
wire   [0:0] icmp_ln40_fu_181_p2;
reg   [0:0] icmp_ln40_reg_347;
wire   [0:0] icmp_ln40_1_fu_187_p2;
reg   [0:0] icmp_ln40_1_reg_352;
reg   [63:0] deltaY_reg_357;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state8_pp0_stage2_iter1;
wire    ap_block_state13_pp0_stage2_iter2;
wire    ap_block_state18_pp0_stage2_iter3;
wire    ap_block_state23_pp0_stage2_iter4;
wire    ap_block_state28_pp0_stage2_iter5;
wire    ap_block_state33_pp0_stage2_iter6;
wire    ap_block_state38_pp0_stage2_iter7;
wire    ap_block_state43_pp0_stage2_iter8;
wire    ap_block_state48_pp0_stage2_iter9;
wire    ap_block_state53_pp0_stage2_iter10;
wire    ap_block_state58_pp0_stage2_iter11;
wire    ap_block_state63_pp0_stage2_iter12;
wire    ap_block_state68_pp0_stage2_iter13;
wire    ap_block_state73_pp0_stage2_iter14;
wire    ap_block_state78_pp0_stage2_iter15;
wire    ap_block_state83_pp0_stage2_iter16;
wire    ap_block_state88_pp0_stage2_iter17;
wire    ap_block_state93_pp0_stage2_iter18;
wire    ap_block_state98_pp0_stage2_iter19;
wire    ap_block_state103_pp0_stage2_iter20;
wire    ap_block_state108_pp0_stage2_iter21;
wire    ap_block_state113_pp0_stage2_iter22;
wire    ap_block_pp0_stage2_11001;
reg   [63:0] deltaY_reg_357_pp0_iter3_reg;
wire   [63:0] determinant_1_fu_203_p3;
reg   [63:0] determinant_1_reg_364;
reg   [63:0] tmp_26_reg_370;
reg   [63:0] tmp_28_reg_375;
reg   [63:0] tmp_32_reg_380;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state4_pp0_stage3_iter0;
wire    ap_block_state9_pp0_stage3_iter1;
wire    ap_block_state14_pp0_stage3_iter2;
wire    ap_block_state19_pp0_stage3_iter3;
wire    ap_block_state24_pp0_stage3_iter4;
wire    ap_block_state29_pp0_stage3_iter5;
wire    ap_block_state34_pp0_stage3_iter6;
wire    ap_block_state39_pp0_stage3_iter7;
wire    ap_block_state44_pp0_stage3_iter8;
wire    ap_block_state49_pp0_stage3_iter9;
wire    ap_block_state54_pp0_stage3_iter10;
wire    ap_block_state59_pp0_stage3_iter11;
wire    ap_block_state64_pp0_stage3_iter12;
wire    ap_block_state69_pp0_stage3_iter13;
wire    ap_block_state74_pp0_stage3_iter14;
wire    ap_block_state79_pp0_stage3_iter15;
wire    ap_block_state84_pp0_stage3_iter16;
wire    ap_block_state89_pp0_stage3_iter17;
wire    ap_block_state94_pp0_stage3_iter18;
wire    ap_block_state99_pp0_stage3_iter19;
wire    ap_block_state104_pp0_stage3_iter20;
wire    ap_block_state109_pp0_stage3_iter21;
wire    ap_block_state114_pp0_stage3_iter22;
wire    ap_block_pp0_stage3_11001;
reg   [63:0] tmp_27_reg_385;
reg   [63:0] tmp_27_reg_385_pp0_iter5_reg;
wire   [63:0] grp_fu_116_p2;
reg   [63:0] tmp_29_reg_390;
reg   [63:0] tmp_33_reg_395;
reg   [63:0] tmp_33_reg_395_pp0_iter5_reg;
reg   [63:0] tmp_33_reg_395_pp0_iter6_reg;
reg   [63:0] tmp_30_reg_400;
reg   [63:0] tmp_31_reg_405;
wire   [63:0] grp_fu_122_p2;
reg   [63:0] tmp_25_reg_410;
reg   [63:0] tmp_34_reg_415;
wire   [63:0] grp_fu_137_p2;
reg   [63:0] tmp_35_reg_420;
reg   [63:0] expTerm_reg_425;
reg   [63:0] tmp_36_reg_430;
reg   [63:0] tmp_36_reg_430_pp0_iter11_reg;
reg   [63:0] tmp_36_reg_430_pp0_iter12_reg;
reg   [63:0] tmp_36_reg_430_pp0_iter13_reg;
reg   [63:0] tmp_36_reg_430_pp0_iter14_reg;
reg   [63:0] tmp_37_reg_435;
wire   [63:0] grp_fu_142_p2;
reg   [63:0] tmp_38_reg_440;
reg   [63:0] denom_reg_445;
wire   [0:0] and_ln43_fu_245_p2;
reg   [0:0] and_ln43_reg_452;
reg   [0:0] and_ln43_reg_452_pp0_iter17_reg;
reg   [0:0] and_ln43_reg_452_pp0_iter18_reg;
reg   [0:0] and_ln43_reg_452_pp0_iter19_reg;
reg   [0:0] and_ln43_reg_452_pp0_iter20_reg;
reg   [0:0] and_ln43_reg_452_pp0_iter21_reg;
reg   [0:0] and_ln43_reg_452_pp0_iter22_reg;
wire   [62:0] trunc_ln368_1_fu_255_p1;
reg   [62:0] trunc_ln368_1_reg_456;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage4_subdone;
reg    ap_block_pp0_stage0_subdone;
reg   [31:0] ap_port_reg_eventY;
reg   [63:0] ap_port_reg_x;
reg   [63:0] ap_port_reg_y;
reg   [63:0] ap_phi_mux_p_0_phi_fu_92_p4;
wire   [63:0] bitcast_ln512_fu_266_p1;
reg   [63:0] ap_phi_reg_pp0_iter23_p_0_reg_88;
wire   [63:0] ap_phi_reg_pp0_iter0_p_0_reg_88;
reg   [63:0] ap_phi_reg_pp0_iter1_p_0_reg_88;
reg   [63:0] ap_phi_reg_pp0_iter2_p_0_reg_88;
reg   [63:0] ap_phi_reg_pp0_iter3_p_0_reg_88;
reg   [63:0] ap_phi_reg_pp0_iter4_p_0_reg_88;
reg   [63:0] ap_phi_reg_pp0_iter5_p_0_reg_88;
reg   [63:0] ap_phi_reg_pp0_iter6_p_0_reg_88;
reg   [63:0] ap_phi_reg_pp0_iter7_p_0_reg_88;
reg   [63:0] ap_phi_reg_pp0_iter8_p_0_reg_88;
reg   [63:0] ap_phi_reg_pp0_iter9_p_0_reg_88;
reg   [63:0] ap_phi_reg_pp0_iter10_p_0_reg_88;
reg   [63:0] ap_phi_reg_pp0_iter11_p_0_reg_88;
reg   [63:0] ap_phi_reg_pp0_iter12_p_0_reg_88;
reg   [63:0] ap_phi_reg_pp0_iter13_p_0_reg_88;
reg   [63:0] ap_phi_reg_pp0_iter14_p_0_reg_88;
reg   [63:0] ap_phi_reg_pp0_iter15_p_0_reg_88;
reg   [63:0] ap_phi_reg_pp0_iter16_p_0_reg_88;
reg   [63:0] ap_phi_reg_pp0_iter17_p_0_reg_88;
reg   [63:0] ap_phi_reg_pp0_iter18_p_0_reg_88;
reg   [63:0] ap_phi_reg_pp0_iter19_p_0_reg_88;
reg   [63:0] ap_phi_reg_pp0_iter20_p_0_reg_88;
reg   [63:0] ap_phi_reg_pp0_iter21_p_0_reg_88;
reg   [63:0] ap_phi_reg_pp0_iter22_p_0_reg_88;
reg   [63:0] grp_fu_99_p0;
reg   [63:0] grp_fu_99_p1;
wire    ap_block_pp0_stage1;
wire    ap_block_pp0_stage2;
wire    ap_block_pp0_stage3;
wire    ap_block_pp0_stage4;
reg   [63:0] grp_fu_103_p0;
reg   [63:0] grp_fu_103_p1;
reg   [63:0] grp_fu_109_p0;
reg   [63:0] grp_fu_109_p1;
reg   [63:0] grp_fu_116_p0;
reg   [63:0] grp_fu_116_p1;
reg   [63:0] grp_fu_122_p1;
reg   [63:0] grp_fu_127_p0;
reg   [31:0] grp_fu_132_p0;
wire   [63:0] p_Val2_s_fu_147_p1;
wire   [62:0] trunc_ln368_fu_150_p1;
wire   [63:0] p_Result_s_fu_158_p3;
wire   [10:0] tmp_287_fu_171_p4;
wire   [51:0] trunc_ln40_fu_154_p1;
wire   [0:0] or_ln40_fu_193_p2;
wire   [0:0] grp_fu_127_p2;
wire   [0:0] and_ln40_fu_197_p2;
wire   [63:0] bitcast_ln43_fu_210_p1;
wire   [10:0] tmp_289_fu_213_p4;
wire   [51:0] trunc_ln43_fu_223_p1;
wire   [0:0] icmp_ln43_1_fu_233_p2;
wire   [0:0] icmp_ln43_fu_227_p2;
wire   [0:0] or_ln43_fu_239_p2;
wire   [63:0] p_Val2_7_fu_251_p1;
wire   [63:0] p_Result_1_fu_259_p3;
reg   [1:0] grp_fu_99_opcode;
wire    ap_block_pp0_stage4_00001;
wire    ap_block_pp0_stage1_00001;
wire    ap_block_pp0_stage2_00001;
wire    ap_block_pp0_stage3_00001;
reg    ap_block_pp0_stage0_00001;
reg    grp_fu_99_ce;
reg    grp_fu_103_ce;
reg    grp_fu_109_ce;
reg    grp_fu_116_ce;
reg    grp_fu_122_ce;
reg    grp_fu_127_ce;
reg    grp_fu_132_ce;
reg    grp_fu_137_ce;
reg    grp_fu_142_ce;
reg   [4:0] ap_NS_fsm;
reg    ap_idle_pp0_0to22;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0_1to23;
reg    ap_block_pp0_stage1_subdone;
reg    ap_block_pp0_stage2_subdone;
reg    ap_block_pp0_stage3_subdone;
wire    ap_enable_pp0;
reg    ap_condition_574;
reg    ap_condition_897;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
end

getTrackerID_hw_dbkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
getTrackerID_hw_dbkb_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_99_p0),
    .din1(grp_fu_99_p1),
    .opcode(grp_fu_99_opcode),
    .ce(grp_fu_99_ce),
    .dout(grp_fu_99_p2)
);

getTrackerID_hw_dcud #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
getTrackerID_hw_dcud_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_103_p0),
    .din1(grp_fu_103_p1),
    .ce(grp_fu_103_ce),
    .dout(grp_fu_103_p2)
);

getTrackerID_hw_dcud #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
getTrackerID_hw_dcud_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_109_p0),
    .din1(grp_fu_109_p1),
    .ce(grp_fu_109_ce),
    .dout(grp_fu_109_p2)
);

getTrackerID_hw_dcud #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
getTrackerID_hw_dcud_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_116_p0),
    .din1(grp_fu_116_p1),
    .ce(grp_fu_116_ce),
    .dout(grp_fu_116_p2)
);

getTrackerID_hw_ddEe #(
    .ID( 1 ),
    .NUM_STAGE( 31 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
getTrackerID_hw_ddEe_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(64'd4607182418800017408),
    .din1(grp_fu_122_p1),
    .ce(grp_fu_122_ce),
    .dout(grp_fu_122_p2)
);

getTrackerID_hw_deOg #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
getTrackerID_hw_deOg_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_127_p0),
    .din1(64'd0),
    .ce(grp_fu_127_ce),
    .opcode(5'd1),
    .dout(grp_fu_127_p2)
);

getTrackerID_hw_sfYi #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
getTrackerID_hw_sfYi_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_132_p0),
    .ce(grp_fu_132_ce),
    .dout(grp_fu_132_p1)
);

getTrackerID_hw_dg8j #(
    .ID( 1 ),
    .NUM_STAGE( 31 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
getTrackerID_hw_dg8j_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(64'd0),
    .din1(determinant_1_reg_364),
    .ce(grp_fu_137_ce),
    .dout(grp_fu_137_p2)
);

getTrackerID_hw_dhbi #(
    .ID( 1 ),
    .NUM_STAGE( 18 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
getTrackerID_hw_dhbi_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(64'd0),
    .din1(tmp_37_reg_435),
    .ce(grp_fu_142_ce),
    .dout(grp_fu_142_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end else if (((ap_enable_reg_pp0_iter22 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter23 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        if ((1'b1 == ap_condition_897)) begin
            ap_phi_reg_pp0_iter16_p_0_reg_88 <= 64'd0;
        end else if ((1'b1 == ap_condition_574)) begin
            ap_phi_reg_pp0_iter16_p_0_reg_88 <= ap_phi_reg_pp0_iter15_p_0_reg_88;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b1 == ap_ce))) begin
        and_ln43_reg_452 <= and_ln43_fu_245_p2;
        and_ln43_reg_452_pp0_iter17_reg <= and_ln43_reg_452;
        and_ln43_reg_452_pp0_iter18_reg <= and_ln43_reg_452_pp0_iter17_reg;
        and_ln43_reg_452_pp0_iter19_reg <= and_ln43_reg_452_pp0_iter18_reg;
        and_ln43_reg_452_pp0_iter20_reg <= and_ln43_reg_452_pp0_iter19_reg;
        and_ln43_reg_452_pp0_iter21_reg <= and_ln43_reg_452_pp0_iter20_reg;
        and_ln43_reg_452_pp0_iter22_reg <= and_ln43_reg_452_pp0_iter21_reg;
        tmp_27_reg_385_pp0_iter5_reg <= tmp_27_reg_385;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        ap_phi_reg_pp0_iter10_p_0_reg_88 <= ap_phi_reg_pp0_iter9_p_0_reg_88;
        expTerm_reg_425 <= grp_fu_116_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        ap_phi_reg_pp0_iter11_p_0_reg_88 <= ap_phi_reg_pp0_iter10_p_0_reg_88;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        ap_phi_reg_pp0_iter12_p_0_reg_88 <= ap_phi_reg_pp0_iter11_p_0_reg_88;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        ap_phi_reg_pp0_iter13_p_0_reg_88 <= ap_phi_reg_pp0_iter12_p_0_reg_88;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        ap_phi_reg_pp0_iter14_p_0_reg_88 <= ap_phi_reg_pp0_iter13_p_0_reg_88;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        ap_phi_reg_pp0_iter15_p_0_reg_88 <= ap_phi_reg_pp0_iter14_p_0_reg_88;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        ap_phi_reg_pp0_iter17_p_0_reg_88 <= ap_phi_reg_pp0_iter16_p_0_reg_88;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        ap_phi_reg_pp0_iter18_p_0_reg_88 <= ap_phi_reg_pp0_iter17_p_0_reg_88;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        ap_phi_reg_pp0_iter19_p_0_reg_88 <= ap_phi_reg_pp0_iter18_p_0_reg_88;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        ap_phi_reg_pp0_iter1_p_0_reg_88 <= ap_phi_reg_pp0_iter0_p_0_reg_88;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        ap_phi_reg_pp0_iter20_p_0_reg_88 <= ap_phi_reg_pp0_iter19_p_0_reg_88;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        ap_phi_reg_pp0_iter21_p_0_reg_88 <= ap_phi_reg_pp0_iter20_p_0_reg_88;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        ap_phi_reg_pp0_iter22_p_0_reg_88 <= ap_phi_reg_pp0_iter21_p_0_reg_88;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter22 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        ap_phi_reg_pp0_iter23_p_0_reg_88 <= ap_phi_reg_pp0_iter22_p_0_reg_88;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        ap_phi_reg_pp0_iter2_p_0_reg_88 <= ap_phi_reg_pp0_iter1_p_0_reg_88;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        ap_phi_reg_pp0_iter3_p_0_reg_88 <= ap_phi_reg_pp0_iter2_p_0_reg_88;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        ap_phi_reg_pp0_iter4_p_0_reg_88 <= ap_phi_reg_pp0_iter3_p_0_reg_88;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        ap_phi_reg_pp0_iter5_p_0_reg_88 <= ap_phi_reg_pp0_iter4_p_0_reg_88;
        tmp_33_reg_395 <= grp_fu_103_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        ap_phi_reg_pp0_iter6_p_0_reg_88 <= ap_phi_reg_pp0_iter5_p_0_reg_88;
        tmp_30_reg_400 <= grp_fu_109_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        ap_phi_reg_pp0_iter7_p_0_reg_88 <= ap_phi_reg_pp0_iter6_p_0_reg_88;
        tmp_31_reg_405 <= grp_fu_99_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        ap_phi_reg_pp0_iter8_p_0_reg_88 <= ap_phi_reg_pp0_iter7_p_0_reg_88;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        ap_phi_reg_pp0_iter9_p_0_reg_88 <= ap_phi_reg_pp0_iter8_p_0_reg_88;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        ap_port_reg_eventY <= eventY;
        ap_port_reg_x <= x;
        ap_port_reg_y <= y;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce))) begin
        deltaX_reg_334 <= grp_fu_99_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b1 == ap_ce))) begin
        deltaY_reg_357 <= grp_fu_99_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b1 == ap_ce))) begin
        deltaY_reg_357_pp0_iter3_reg <= deltaY_reg_357;
        determinant_1_reg_364[62 : 0] <= determinant_1_fu_203_p3[62 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter16 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce))) begin
        denom_reg_445 <= grp_fu_109_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce))) begin
        determinant_reg_341[62 : 0] <= determinant_fu_166_p1[62 : 0];
        icmp_ln40_1_reg_352 <= icmp_ln40_1_fu_187_p2;
        icmp_ln40_reg_347 <= icmp_ln40_fu_181_p2;
        tmp_36_reg_430_pp0_iter11_reg <= tmp_36_reg_430;
        tmp_36_reg_430_pp0_iter12_reg <= tmp_36_reg_430_pp0_iter11_reg;
        tmp_36_reg_430_pp0_iter13_reg <= tmp_36_reg_430_pp0_iter12_reg;
        tmp_36_reg_430_pp0_iter14_reg <= tmp_36_reg_430_pp0_iter13_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        p_x_assign_reg_329 <= grp_fu_99_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        sigmaXY_read_reg_271 <= sigmaXY;
        sigmaXY_read_reg_271_pp0_iter1_reg <= sigmaXY_read_reg_271;
        sigmaXY_read_reg_271_pp0_iter2_reg <= sigmaXY_read_reg_271_pp0_iter1_reg;
        sigmaXY_read_reg_271_pp0_iter3_reg <= sigmaXY_read_reg_271_pp0_iter2_reg;
        sigmaXY_read_reg_271_pp0_iter4_reg <= sigmaXY_read_reg_271_pp0_iter3_reg;
        sigmaX_read_reg_283 <= sigmaX;
        sigmaX_read_reg_283_pp0_iter1_reg <= sigmaX_read_reg_283;
        sigmaX_read_reg_283_pp0_iter2_reg <= sigmaX_read_reg_283_pp0_iter1_reg;
        sigmaX_read_reg_283_pp0_iter3_reg <= sigmaX_read_reg_283_pp0_iter2_reg;
        sigmaY_read_reg_277 <= sigmaY;
        sigmaY_read_reg_277_pp0_iter1_reg <= sigmaY_read_reg_277;
        sigmaY_read_reg_277_pp0_iter2_reg <= sigmaY_read_reg_277_pp0_iter1_reg;
        sigmaY_read_reg_277_pp0_iter3_reg <= sigmaY_read_reg_277_pp0_iter2_reg;
        tmp_35_reg_420 <= grp_fu_137_p2;
        tmp_38_reg_440 <= grp_fu_142_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        tmp_23_reg_314 <= grp_fu_103_p2;
        tmp_24_reg_319 <= grp_fu_109_p2;
        tmp_reg_309 <= grp_fu_132_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b1 == ap_ce))) begin
        tmp_25_reg_410 <= grp_fu_122_p2;
        tmp_34_reg_415 <= grp_fu_99_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b1 == ap_ce))) begin
        tmp_26_reg_370 <= grp_fu_103_p2;
        tmp_28_reg_375 <= grp_fu_109_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b1 == ap_ce))) begin
        tmp_27_reg_385 <= grp_fu_109_p2;
        tmp_29_reg_390 <= grp_fu_116_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b1 == ap_ce))) begin
        tmp_32_reg_380 <= grp_fu_103_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        tmp_33_reg_395_pp0_iter5_reg <= tmp_33_reg_395;
        tmp_33_reg_395_pp0_iter6_reg <= tmp_33_reg_395_pp0_iter5_reg;
        x_read_reg_304 <= ap_port_reg_x;
        y_read_reg_299 <= ap_port_reg_y;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce))) begin
        tmp_36_reg_430 <= grp_fu_103_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        tmp_37_reg_435 <= grp_fu_116_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce))) begin
        tmp_s_reg_324 <= grp_fu_132_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln43_reg_452_pp0_iter22_reg) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        trunc_ln368_1_reg_456 <= trunc_ln368_1_fu_255_p1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter23 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce)) | ((ap_start == 1'b0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_idle_pp0 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to22 = 1'b1;
    end else begin
        ap_idle_pp0_0to22 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0))) begin
        ap_idle_pp0_1to23 = 1'b1;
    end else begin
        ap_idle_pp0_1to23 = 1'b0;
    end
end

always @ (*) begin
    if (((1'd0 == and_ln43_reg_452_pp0_iter22_reg) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter23 == 1'b1))) begin
        ap_phi_mux_p_0_phi_fu_92_p4 = bitcast_ln512_fu_266_p1;
    end else begin
        ap_phi_mux_p_0_phi_fu_92_p4 = ap_phi_reg_pp0_iter23_p_0_reg_88;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to22 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001))))) begin
        grp_fu_103_ce = 1'b1;
    end else begin
        grp_fu_103_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_103_p0 = tmp_35_reg_420;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_103_p0 = tmp_32_reg_380;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_103_p0 = deltaY_reg_357;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_103_p0 = deltaX_reg_334;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_103_p0 = sigmaX;
    end else begin
        grp_fu_103_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_103_p1 = 64'd4618760256179416344;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_103_p1 = sigmaX_read_reg_283_pp0_iter3_reg;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_103_p1 = deltaY_reg_357;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_103_p1 = deltaX_reg_334;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_103_p1 = sigmaY;
    end else begin
        grp_fu_103_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001))))) begin
        grp_fu_109_ce = 1'b1;
    end else begin
        grp_fu_109_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter15 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_109_p0 = tmp_36_reg_430_pp0_iter14_reg;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_109_p0 = tmp_29_reg_390;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_109_p0 = tmp_26_reg_370;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_109_p0 = deltaX_reg_334;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_109_p0 = sigmaXY;
    end else begin
        grp_fu_109_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter15 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_109_p1 = tmp_38_reg_440;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_109_p1 = sigmaXY_read_reg_271_pp0_iter4_reg;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_109_p1 = sigmaY_read_reg_277_pp0_iter3_reg;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_109_p1 = 64'd4611686018427387904;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_109_p1 = sigmaXY;
    end else begin
        grp_fu_109_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001))))) begin
        grp_fu_116_ce = 1'b1;
    end else begin
        grp_fu_116_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_116_p0 = expTerm_reg_425;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_116_p0 = tmp_25_reg_410;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_116_p0 = tmp_28_reg_375;
    end else begin
        grp_fu_116_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_116_p1 = 64'd4602678819172646912;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_116_p1 = tmp_34_reg_415;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_116_p1 = deltaY_reg_357_pp0_iter3_reg;
    end else begin
        grp_fu_116_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001))))) begin
        grp_fu_122_ce = 1'b1;
    end else begin
        grp_fu_122_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter16 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_122_p1 = denom_reg_445;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_122_p1 = determinant_1_reg_364;
    end else begin
        grp_fu_122_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))))) begin
        grp_fu_127_ce = 1'b1;
    end else begin
        grp_fu_127_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter16 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_127_p0 = denom_reg_445;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_127_p0 = determinant_fu_166_p1;
    end else begin
        grp_fu_127_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001))))) begin
        grp_fu_132_ce = 1'b1;
    end else begin
        grp_fu_132_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_132_p0 = ap_port_reg_eventY;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_132_p0 = eventX;
        end else begin
            grp_fu_132_p0 = 'bx;
        end
    end else begin
        grp_fu_132_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001))))) begin
        grp_fu_137_ce = 1'b1;
    end else begin
        grp_fu_137_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001))))) begin
        grp_fu_142_ce = 1'b1;
    end else begin
        grp_fu_142_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001))))) begin
        grp_fu_99_ce = 1'b1;
    end else begin
        grp_fu_99_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_00001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_00001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_00001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_00001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_99_opcode = 2'd1;
    end else if (((1'b0 == ap_block_pp0_stage4_00001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_99_opcode = 2'd0;
    end else begin
        grp_fu_99_opcode = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_99_p0 = tmp_31_reg_405;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_99_p0 = tmp_27_reg_385_pp0_iter5_reg;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        grp_fu_99_p0 = tmp_s_reg_324;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_99_p0 = tmp_reg_309;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_99_p0 = tmp_23_reg_314;
    end else begin
        grp_fu_99_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_99_p1 = tmp_33_reg_395_pp0_iter6_reg;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_99_p1 = tmp_30_reg_400;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        grp_fu_99_p1 = y_read_reg_299;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_99_p1 = x_read_reg_304;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_99_p1 = tmp_24_reg_319;
    end else begin
        grp_fu_99_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start == 1'b0) & (ap_idle_pp0_1to23 == 1'b1)) & (ap_reset_idle_pp0 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln40_fu_197_p2 = (or_ln40_fu_193_p2 & grp_fu_127_p2);

assign and_ln43_fu_245_p2 = (or_ln43_fu_239_p2 & grp_fu_127_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_00001 = ((ap_start == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b0 == ap_ce) | ((ap_start == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_subdone = (1'b0 == ap_ce);
end

assign ap_block_state100_pp0_stage4_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state101_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state102_pp0_stage1_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state103_pp0_stage2_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state104_pp0_stage3_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state105_pp0_stage4_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state106_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state107_pp0_stage1_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state108_pp0_stage2_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state109_pp0_stage3_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage4_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state110_pp0_stage4_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state111_pp0_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state112_pp0_stage1_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state113_pp0_stage2_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state114_pp0_stage3_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state115_pp0_stage4_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state116_pp0_stage0_iter23 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage4_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage3_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start == 1'b0);
end

assign ap_block_state20_pp0_stage4_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage2_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage3_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage4_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage1_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage2_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage3_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage4_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage1_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage2_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage3_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage4_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state37_pp0_stage1_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state38_pp0_stage2_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state39_pp0_stage3_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state40_pp0_stage4_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state41_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state42_pp0_stage1_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state43_pp0_stage2_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state44_pp0_stage3_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state45_pp0_stage4_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state46_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state47_pp0_stage1_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state48_pp0_stage2_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state49_pp0_stage3_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state50_pp0_stage4_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state51_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state52_pp0_stage1_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state53_pp0_stage2_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state54_pp0_stage3_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state55_pp0_stage4_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state56_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state57_pp0_stage1_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state58_pp0_stage2_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state59_pp0_stage3_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state60_pp0_stage4_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state61_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state62_pp0_stage1_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state63_pp0_stage2_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state64_pp0_stage3_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state65_pp0_stage4_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state66_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state67_pp0_stage1_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state68_pp0_stage2_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state69_pp0_stage3_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state70_pp0_stage4_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state71_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state72_pp0_stage1_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state73_pp0_stage2_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state74_pp0_stage3_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state75_pp0_stage4_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state76_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state77_pp0_stage1_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state78_pp0_stage2_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state79_pp0_stage3_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state80_pp0_stage4_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state81_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state82_pp0_stage1_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state83_pp0_stage2_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state84_pp0_stage3_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state85_pp0_stage4_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state86_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state87_pp0_stage1_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state88_pp0_stage2_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state89_pp0_stage3_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state90_pp0_stage4_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state91_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state92_pp0_stage1_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state93_pp0_stage2_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state94_pp0_stage3_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state95_pp0_stage4_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state96_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state97_pp0_stage1_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state98_pp0_stage2_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state99_pp0_stage3_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_574 = ((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001));
end

always @ (*) begin
    ap_condition_897 = ((1'd1 == and_ln43_fu_245_p2) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter16 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_p_0_reg_88 = 'bx;

assign ap_return = ap_phi_mux_p_0_phi_fu_92_p4;

assign bitcast_ln43_fu_210_p1 = denom_reg_445;

assign bitcast_ln512_fu_266_p1 = p_Result_1_fu_259_p3;

assign determinant_1_fu_203_p3 = ((and_ln40_fu_197_p2[0:0] === 1'b1) ? 64'd4607182418800017408 : determinant_reg_341);

assign determinant_fu_166_p1 = p_Result_s_fu_158_p3;

assign icmp_ln40_1_fu_187_p2 = ((trunc_ln40_fu_154_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln40_fu_181_p2 = ((tmp_287_fu_171_p4 != 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln43_1_fu_233_p2 = ((trunc_ln43_fu_223_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln43_fu_227_p2 = ((tmp_289_fu_213_p4 != 11'd2047) ? 1'b1 : 1'b0);

assign or_ln40_fu_193_p2 = (icmp_ln40_reg_347 | icmp_ln40_1_reg_352);

assign or_ln43_fu_239_p2 = (icmp_ln43_fu_227_p2 | icmp_ln43_1_fu_233_p2);

assign p_Result_1_fu_259_p3 = {{1'd0}, {trunc_ln368_1_reg_456}};

assign p_Result_s_fu_158_p3 = {{1'd0}, {trunc_ln368_fu_150_p1}};

assign p_Val2_7_fu_251_p1 = grp_fu_122_p2;

assign p_Val2_s_fu_147_p1 = p_x_assign_reg_329;

assign tmp_287_fu_171_p4 = {{p_Val2_s_fu_147_p1[62:52]}};

assign tmp_289_fu_213_p4 = {{bitcast_ln43_fu_210_p1[62:52]}};

assign trunc_ln368_1_fu_255_p1 = p_Val2_7_fu_251_p1[62:0];

assign trunc_ln368_fu_150_p1 = p_Val2_s_fu_147_p1[62:0];

assign trunc_ln40_fu_154_p1 = p_Val2_s_fu_147_p1[51:0];

assign trunc_ln43_fu_223_p1 = bitcast_ln43_fu_210_p1[51:0];

always @ (posedge ap_clk) begin
    determinant_reg_341[63] <= 1'b0;
    determinant_1_reg_364[63] <= 1'b0;
end

endmodule //GaussianP
